user:
  avatar_width: 200
  avatar_height: 200
  avatar_size: 2
  avatar_type: "image/jpeg,image/gif,image/png"
  max_name: 50
  max_email: 255
  min_password: 6
  password_reset_expired: 2
  page_size: 10
category:
  page_size: 10
  min_words: 15
  empty: 0
word:
  page_size: 15
  max_answers: 4
  max_new_per_form: 5
